"""Create models for WOD

Revision ID: 2eab50435004
Revises: 505a8b5dc18e
Create Date: 2021-03-20 11:39:08.426631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eab50435004'
down_revision = '505a8b5dc18e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
