"""Fix relationships between Wod and WodType

Revision ID: 3213fa674981
Revises: 8f6378b72002
Create Date: 2021-03-23 12:08:59.164675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3213fa674981"
down_revision = "8f6378b72002"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "wod_type", ["name"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "wod_type", type_="unique")
    # ### end Alembic commands ###
