"""Remove wod_type relationship

Revision ID: 8f6378b72002
Revises: f36d13f81346
Create Date: 2021-03-22 18:56:03.034974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8f6378b72002"
down_revision = "f36d13f81346"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
