"""Add nullable on user's required fields

Revision ID: b1aad446a2b6
Revises: be6a5a92b2ef
Create Date: 2021-03-31 23:15:34.548161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b1aad446a2b6"
down_revision = "be6a5a92b2ef"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("user", "username", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "username", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("user", "email", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
