"""Fix relationships between Wod and Round

Revision ID: be6a5a92b2ef
Revises: 3213fa674981
Create Date: 2021-03-23 19:41:00.480490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "be6a5a92b2ef"
down_revision = "3213fa674981"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("round", "wod_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint("round_parent_id_fkey", "round", type_="foreignkey")
    op.drop_column("round", "parent_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "round",
        sa.Column("parent_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "round_parent_id_fkey", "round", "round", ["parent_id"], ["id"]
    )
    op.alter_column("round", "wod_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
