"""Rename children to sub_rounds in round

Revision ID: c459fe01acc1
Revises: 40b94ed520f0
Create Date: 2021-04-11 19:30:01.162855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c459fe01acc1"
down_revision = "40b94ed520f0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("round", sa.Column("parent_round_id", sa.Integer(), nullable=True))
    op.drop_constraint("round_parent_id_fkey", "round", type_="foreignkey")
    op.create_foreign_key(None, "round", "round", ["parent_round_id"], ["id"])
    op.drop_column("round", "parent_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "round",
        sa.Column("parent_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "round", type_="foreignkey")
    op.create_foreign_key(
        "round_parent_id_fkey", "round", "round", ["parent_id"], ["id"]
    )
    op.drop_column("round", "parent_round_id")
    # ### end Alembic commands ###
