pull_request_rules:
  - name: Merge Guillaume's pull requests
    conditions:
      - author=GuillaumeOj
      - label!=manual merge
      - check-success~=^security/snyk
      - check-success=py39
      - check-success=pep8
    actions:
      merge:
        strict: "smart"
        method: rebase
      delete_head_branch:
        force: True
  - name: Warn on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: This pull request is now in conflict 😕
      label:
        add:
          - conflict
  - name: Remove conflict label
    conditions:
      - -conflict
    actions:
      label:
        remove:
          - conflict
  - name: Merge Snyk's pull requests
    conditions:
      - title~=^\[Snyk\]
      - head~=^snyk-fix
      - check-success~=^security/snyk
      - check-success=py39
      - check-success=pep8
    actions:
      merge:
        strict: "smart"
        method: rebase
