pull_request_rules:
  - name: Merge Guillaume's pull requests
    conditions:
      - author=GuillaumeOj
      - "label!=manual merge"
      - "check-success=py39"
      - "check-success=pep8"
      - "check-success=coverage"
    actions:
      merge:
        strict: "smart"
        method: rebase
      delete_head_branch:
        force: True
  - name: Warn on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: This pull request is now in conflict 😕
      label:
        add:
          - conflict
  - name: Remove conflict label
    conditions:
      - -conflict
    actions:
      label:
        remove:
          - conflict
  - name: Merge Dependabot's pull requests
    conditions:
      - "author=dependabot[bot]"
      - "label!=manual merge"
      - "check-success=py39"
      - "check-success=pep8"
      - "check-success=coverage"
    actions:
      merge:
        strict: "smart"
        method: rebase
