"""empty message

Revision ID: 44babe44ded5
Revises: b1aad446a2b6
Create Date: 2021-04-07 14:55:08.371654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "44babe44ded5"
down_revision = "b1aad446a2b6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("round", sa.Column("parent_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "round", "round", ["parent_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "round", type_="foreignkey")
    op.drop_column("round", "parent_id")
    # ### end Alembic commands ###
