"""empty message

Revision ID: 865d47baf506
Revises: c459fe01acc1
Create Date: 2021-04-13 20:43:29.288896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "865d47baf506"
down_revision = "c459fe01acc1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movement_goal",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("movement_id", sa.Integer(), nullable=True),
        sa.Column("repetition", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["movement_id"],
            ["movement.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "movement_goal_equipment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("movement_goal_id", sa.Integer(), nullable=True),
        sa.Column("equipment_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["equipment_id"],
            ["equipment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["movement_goal_id"],
            ["movement_goal.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "round_movement_goal",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("round_id", sa.Integer(), nullable=True),
        sa.Column("movement_goal_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["movement_goal_id"],
            ["movement_goal.id"],
        ),
        sa.ForeignKeyConstraint(
            ["round_id"],
            ["round.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("round", sa.Column("parent_id", sa.Integer(), nullable=True))
    op.alter_column("round", "wod_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint("round_parent_round_id_fkey", "round", type_="foreignkey")
    op.create_foreign_key(None, "round", "round", ["parent_id"], ["id"])
    op.drop_column("round", "parent_round_id")
    op.alter_column("wod", "wod_type_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("wod", "wod_type_id", existing_type=sa.INTEGER(), nullable=False)
    op.add_column(
        "round",
        sa.Column("parent_round_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "round", type_="foreignkey")
    op.create_foreign_key(
        "round_parent_round_id_fkey", "round", "round", ["parent_round_id"], ["id"]
    )
    op.alter_column("round", "wod_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("round", "parent_id")
    op.drop_table("round_movement_goal")
    op.drop_table("movement_goal_equipment")
    op.drop_table("movement_goal")
    # ### end Alembic commands ###
