name: CI

on:
  pull_request:
    branches: [main]

jobs:
  pep8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Install tox
        run: python -m pip install tox
      - name: Run tests
        run: tox -e pep8
  py39:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: "wod_board"
          POSTGRES_PASSWORD: "wod_board"
          POSTGRES_DB: "wod_board_test"
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Install tox
        run: python -m pip install tox
      - name: Run tests
        env:
          DATABASE_URL: postgresql://wod_board:wod_board@localhost/wod_board_test
        run: tox -e py39
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install
      - name: Run eslint
        run: yarn eslint
  front-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install
      - name: Build React App
        run: yarn build
