name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  pep8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install tox
      run: python -m pip install tox
    - name: Run tests 
      run: tox -e pep8
  py39:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: 'wod_board'
          POSTGRES_PASSWORD: 'wod_board'
          POSTGRES_DB: 'wod_board'
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install tox
      run: python -m pip install tox
    - name: Run tests 
      env:
        DATABASE_URL: postgresql://wod_board:wod_board@localhost:5432/wod_board
      run: tox -e py39
  coverage:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: 'wod_board'
          POSTGRES_PASSWORD: 'wod_board'
          POSTGRES_DB: 'wod_board'
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install tox
      run: python -m pip install tox
    - name: Run coverage 
      env:
        DATABASE_URL: postgresql://wod_board:wod_board@localhost:5432/wod_board
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: tox -e coverage
